spring:
  datasource:
    data: 'classpath:R__1_13__MOVEMENT_REASONS.sql,
          classpath:R__1_15__OFFENDERS.sql,
          classpath:R__1_2__ADDRESSES.sql,
          classpath:R__3_6_1__OFFENDER_BOOKINGS.sql,
          classpath:R__3_7__OFFENDER_IDENTIFIERS.sql,
          classpath:R__4_5__OFFENDER_CASES.sql,
          classpath:R__4_7__OFFENDER_EXTERNAL_MOVEMENTS.sql,
          classpath:R__5_2__OFFENDER_CHARGES.sql,
          classpath:R__5_6__ORDERS.sql,
          classpath:R__6_3__OFFENDER_SENTENCES.sql,
          classpath:R__1_4__ASSESSMENTS.sql,
          classpath:R__4_4__OFFENDER_ASSESSMENTS.sql,
          classpath:some_health_problems.sql'

  jpa:
    hibernate:
      ddl-auto: create

