spring:
  datasource:
    data: 'classpath:R__1_2__ADDRESSES.sql,
          classpath:R__1_4__ASSESSMENTS.sql,
          classpath:R__1_6__CONTACT_PERSON_TYPES.sql,
          classpath:R__1_9__HO_CODES.sql,
          classpath:R__1_10__IMPRISONMENT_STATUSES.sql,
          classpath:R__1_13__MOVEMENT_REASONS.sql,
          classpath:R__1_15__OFFENDERS.sql,
          classpath:R__1_19__PERSONS.sql,
          classpath:R__1_20__PHONES.sql,
          classpath:R__1_21__PROFILE_CODES.sql,
          classpath:R__1_26__STATUTES.sql,
          classpath:R__2_1__AGENCY_LOCATIONS.sql,
          classpath:R__2_2__OFFENCES.sql,
          classpath:R__2_3__REFERENCE_CODES.sql,
          classpath:R__3_2__AGENCY_INTERNAL_LOCATIONS.sql,
          classpath:R__3_4__COURSE_ACTIVITIES.sql,
          classpath:R__3_5__IEP_LEVELS.sql,
          classpath:R__3_6_1__OFFENDER_BOOKINGS.sql,
          classpath:R__3_7__OFFENDER_IDENTIFIERS.sql,
          classpath:R__4_2__COURSE_SCHEDULES.sql,
          classpath:R__4_3__OFFENDER_ALERTS.sql,
          classpath:R__4_4__OFFENDER_ASSESSMENTS.sql,
          classpath:R__4_5__OFFENDER_CASES.sql,
          classpath:R__4_6__OFFENDER_CONTACT_PERSONS.sql,
          classpath:R__4_7__OFFENDER_EXTERNAL_MOVEMENTS.sql,
          classpath:R__4_8__OFFENDER_IDENTIFYING_MARKS.sql,
          classpath:R__4_9__OFFENDER_IEP_LEVELS.sql,
          classpath:R__4_11__OFFENDER_IMPRISON_STATUSES.sql,
          classpath:R__4_15__OFFENDER_PHYSICAL_ATTRIBUTES.sql,
          classpath:R__4_17__OFFENDER_PROFILE_DETAILS.sql,
          classpath:R__4_18__OFFENDER_RELEASE_DETAILS.sql,
          classpath:R__4_19__OFFENDER_SENT_CALCULATIONS.sql,
          classpath:R__5_2__OFFENDER_CHARGES.sql,
          classpath:R__5_3__OFFENDER_IND_SCHEDULES.sql,
          classpath:R__5_4__OFFENDER_PROGRAM_PROFILES.sql,
          classpath:R__5_6__ORDERS.sql,
          classpath:R__6_1__OFFENDER_COURSE_ATTENDANCES.sql,
          classpath:R__6_2__OFFENDER_EXCLUDES_ACTS_SCHDS.sql,
          classpath:R__6_3__OFFENDER_SENTENCES.sql,
          classpath:some_health_problems.sql,
          classpath:some_address_usages.sql,
          classpath:some_offence_indicators.sql,
          classpath:some_employments.sql,
          classpath:some_court_events.sql,
          classpath:some_court_event_charges.sql,
          classpath:some_offender_sentence_charges.sql,
          classpath:some_offender_rehab_decisions.sql,
          classpath:some_offender_rehab_providers.sql,
          classpath:some_offender_images.sql,
          classpath:some_offender_events.sql'

  jpa:
    hibernate:
      ddl-auto: create


  h2:
    console:
      enabled: true

hibernate:
  hbm2ddl:


